name: CI/CD Pipeline Build Docker

on:
  push:
    paths:
      - 'Workflow-CI/**'  # Trigger hanya jika folder ini berubah

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: ${{ secrets.DAGSHUB_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow==2.11.3 pandas scikit-learn numpy

    - name: Run Training (Generate Model)
      run: |
        cd Workflow-CI/MLProject
        python modelling.py
        # Cek apakah run_id.txt terbentuk
        cat run_id.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        # Ambil Run ID dari file yang dibuat script python
        cd Workflow-CI/MLProject
        RUN_ID=$(cat run_id.txt)
        echo "Building Docker for Run ID: $RUN_ID"
        
        # Nama Image (ganti 'username' dengan username docker hub asli Anda!)
        DOCKER_IMAGE="${{ secrets.DOCKER_USERNAME }}/submission-mlops:latest"
        
        # Perintah ajaib MLflow untuk build docker
        mlflow models build-docker \
          --model-uri "runs:/$RUN_ID/model" \
          --name "$DOCKER_IMAGE" \
          --enable-mlserver
          
        # Push ke Docker Hub
        docker push "$DOCKER_IMAGE"